spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/kneeonbelly
    username: kneeonbelly
    password: kneeonbelly123
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
logging:
  level:
    org.springframework: info